### ISSUE TITLE
Internet Data Drain While Online Watching

### ISSUE THREAD

**Issue by AuraNight80** [recloudstream/cloudstream#1018]
### Steps to reproduce

Watch Anything It Will Take More Or Double Amount Of Internet Data It Is Of Size While Online Watch.
When We Watch Online It Takes More Data Then It Is Of Size LIKE If We Watch 500MB Movie Online It Will Take 900 MB Why Can't You Add Some Data Saving Feature?

### Expected behavior

It Should Have Take The Data It Is Showing It Is Of Size In App.

### Actual behavior

It Takes It Double Internet Data Of Size It Is Movie Anime Etc.

### Cloudstream version and commit hash

4.3.0 3c152e04

### Android version

12

### Logcat

```java
--------- beginning of main
03-29 20:28:16.518  9463  9463 D ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4412)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4454)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4836)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4806)] [com.google.android.gms.internal.cast.zzdc.zza(com.google.android.gms:play-services-cast@@21.3.0:6)] [com.google.android.gms.internal.cast.zzcx.<init>(com.google.android.gms:play-services-cast@@21.3.0:4)] [com.google.android.gms.cast.framework.CastContext.<init>(com.google.android.gms:play-services-cast-framework@@21.3.0:14)] [com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@21.3.0:10)] [com.lagradost.cloudstream3.utils.AppUtils.isCastApiAvailable(AppUtils.kt:687)] [com.lagradost.cloudstream3.MainActivity.onCreate(MainActivity.kt:1089)] [android.app.Activity.performCreate(Activity.java:8290)] [android.app.Activity.performCreate(Activity.java:8270)] [android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)] [android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)] [android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)] [android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)] [android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)] [android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)] [android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)]
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by AuraNight80** [comment]
> `com.google.android.gms.internal.cast.zzdc.zza(com.google.android.gms:play-services-cast@@21.3.0:6)` Broadcast on TV?

No On Android Mobile.

**Comment by AuraNight80** [comment]
You Should Add A Compression Proxy With Settingd Like Low,Mid,High Compression Or Any Other Data Saving Features.

**Comment by AuraNight80** [comment]
> `com.google.android.gms.internal.cast.zzdc.zza(com.google.android.gms:play-services-cast@@21.3.0:6)` Broadcast on TV?

You Should Add  A Compression Proxy With Options Like Low,Mid,High Compression Or Any Other Data Saving Features.

**Comment by fire-light42** [comment]
We dont host the servers, we cant do server sided compression

**Comment by Luna712** [comment]
@fire-light42 I'm pretty sure excessive data usage is caused by the thumbnail preview, which was one of my initial reasons of requesting a preference to toggle that, however understandably you didn't want to to bloat the settings, however I still do find it a valid reasons, and maybe could be considered? If not that's totally okay, I understand.

**Comment by fire-light42** [comment]
Sure add option for that

**Comment by M-BOUAB** [comment]
> @fire-light42 I'm pretty sure excessive data usage is caused by the thumbnail preview, which was one of my initial reasons of requesting a preference to toggle that, however understandably you didn't want to to bloat the settings, however I still do find it a valid reasons, and maybe could be considered? If not that's totally okay, I understand.

I've heard this thing from the devs about fear of bloating the settings menu. It's just a weird fear to have imo, I'm not saying that you should bloat the settings menu, it's your app, but I just find it weird that some of the biggest most successful apps & platforms all have setting menus that are so big, you can't even scroll through them all.
I think it's about managing the settings the right way so that it's most useful. Apple is the company that created the idea of minimalism & simplicity in it's design, & their iOS settings menu is still the biggest in any phone os after Huawei Harmonyos.
I suggest you add any new option that could bloat the settings menu to an advanced settings section, & hide the section below a long click on the settings menu, this way, simple people are still happy the settings aren't bloated, & smart curious people are also having fun. Or you can just add the options & not worry about it, cuz most android users are used to long settings menu from social media apps or from mods of those social media apps.
Even my alarm clock app has more settings than cloudstream if you know what I mean :)

**Comment by Luna712** [comment]
> Sure add option for that

@fire-light42

Thanks, I plan to do a patch for this at some point, but I have a question so I don't do useless work. Since currently it is just disabled on TV should I (1) make it ignore the preference and TV entirely and remain disabled or (2) default the preference to disabled on TV and enabled on phone and emulator (if that is even possible, which I haven't looked into yet) — another thing while I am at it, would you like me to make [UPDATE_SYNC_PROGRESS_PERCENTAGE](https://github.com/recloudstream/cloudstream/blob/0a24661e4cf301fac304ce6f28f32b718fdc81b1/app/src/main/java/com/lagradost/cloudstream3/ui/player/AbstractPlayerFragment.kt#L72) a setting while I am at it to complete that TODO comment or not? Just wondering.
