### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#1176]
Since #1163, I have had to locally revert to let me build or run again. There was an issue with MainAPI that was fixed but now I get:

```
Cannot locate tasks that match ':library:testClasses' as task 'testClasses' not found in project ':library'. Some candidates are: 'jvmTestClasses'.
```
When trying to rebuild, and:

```
e: file:///C:/Users/---/AndroidStudioProjects/cloudstream3-new/app/src/main/java/com/lagradost/cloudstream3/metaproviders/SyncRedirector.kt:47:48 Cannot access class 'com.lagradost.cloudstream3.syncproviders.SyncIdName'. Check your module classpath for missing or conflicting dependencies
```

When trying to run app, I even tried a fresh clone, but nothing seems to work.

**Comment by CranberrySoup** [comment]
I cannot replicate the error on a clean build. Perhaps invalidate your caches?
Are you building with android studio UI or using some command?

I do however get one issue with https://github.com/recloudstream/cloudstream/blob/master/app/src/androidTest/java/com/lagradost/cloudstream3/ExampleInstrumentedTest.kt because it was not migrated in https://github.com/recloudstream/cloudstream/pull/1142

**Comment by Luna712** [comment]
> I cannot replicate the error on a clean build. Perhaps invalidate your caches? Given that github actions complete the build it is likely something on your machine Are you building with android studio UI or using some command?
> 
> I do however get one issue with https://github.com/recloudstream/cloudstream/blob/master/app/src/androidTest/java/com/lagradost/cloudstream3/ExampleInstrumentedTest.kt because it was not migrated in #1142

I am using UI yes, I did invalidate cache -- did not work, however I reinstalled android studio with a new version and it did work. So closing this. Sorry, it must have indeed been a me issue.
