### ISSUE TITLE
Ability to play Local Vids

### ISSUE THREAD

**Issue by Adbc3949** [recloudstream/cloudstream#119]
### Describe your suggested feature

Ability of App to Show and play any Local Vids on phone and not just the Vids downloaded through the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
you can do that already.
1. find ang video file in a file explorer
2. share > open in cloudstream
3. ???
4. profit

**Comment by Adbc3949** [comment]
No I meant like Ability of App to Display Local Vids within the App and also play ofc

**Comment by AbdulSamadMalik** [comment]
> No I meant like Ability of App to Display Local Vids within the App and also play ofc

Bro there are plenty of good and open source video players out there, so what's the point of displaying local videos in a online video streaming app, even I sometimes don't use CloudStream's Player for playing videos because other player can play better with more options, some of my favorites are listed below:

### Open Source & Ad free
- [NOVA Video Player (Best)
](https://play.google.com/store/apps/details?id=org.courville.nova)
- [MPV for Android](https://play.google.com/store/apps/details?id=is.xyz.mpv)
- [VLC for Android](https://play.google.com/store/apps/details?id=org.videolan.vlc)

### Proprietary
- [Video Player All Format](https://play.google.com/store/apps/details?id=video.player.videoplayer)

**Comment by LagradOst** [comment]
already exist
