### ISSUE TITLE
Select search icon twice to open keyboard

### ISSUE THREAD

**Issue by 6daemonbeg** [recloudstream/cloudstream#1195]
### Describe your suggested feature

Currently, when a user selects the Search icon they are taken to the Search page with the cursor active in the search bar, and the keyboard is not pulled up.

I would like to suggest setting a secondary trigger- When a user is on the Search page and selects the search icon again, the keyboard is pulled up on the screen. 

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by DucksInParks** [comment]
This is common in multiple UIs, including those of Google. It would help with reachability and user experience. But I think it would be even better if the search field was activated right away even on single taps, since per M3, "While search view is typically displayed after a user taps search bar, search view can also serve as the primary focus state if searching is intended to be the user’s primary action." (https://m3.material.io/components/search/guidelines)

Users can easily view the most important history items (the recent ones) even when the keyboard is open, and can easily lower it to more easily navigate their history.

**Comment by 6daemonbeg** [comment]
Thanks for the UX guidelines reference. I wasn't sure if a single tap to the search page should also trigger the "search view," since not all apps behave similarly (ex. Instagram). I guess it depends on developer intensions. 

However, you are right on the money regarding reachability. I'm absolutely for single- or double-tap to trigger the keyboard.

**Comment by fire-light42** [comment]
This has been requested *AND* implemented several times. However due to Android being retarded on some lower api levels and on some roms, doing any sort of focus via code will lead to major bugs with things like the keyboard never disappearing or appearing when not on search randomly. This makes the search completely unusable for some people, and as such has been chosen to be avoided due to these bugs.
