### ISSUE TITLE
add cache when searching

### ISSUE THREAD

**Issue by Turhvjbufv** [recloudstream/cloudstream#1307]
### Describe your suggested feature

If I press on an entry, then exit it and go to another entry and then go back, it cause the entry to load again, I'm thinking cache would be much better as there's barely any chance that the entry stuff changed in the short time you search

### Other details

Maybe add pull to refresh gesture in entries to counter the potential problem 

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
Content should be cached for 10min or the last 20 entries, however the loading might still be there, because even if the result is cached it has to process that cache for series with a lot of episodes. 

https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/ui/APIRepository.kt#L84
