### ISSUE TITLE
Any plans to add this to other OS?

### ISSUE THREAD

**Issue by sryu1** [recloudstream/cloudstream#171]
### Describe your suggested feature

Is there any chance this app will be created to work in also other OS such as windows, linux, IOS?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
on windows: [readme](https://cloudflare-ipfs.com/ipns/cloudstream.cf/docs/users/wsa.md)

on linux: anbox or waydroid

ios: nahhh

**Comment by rokejulianlockhart** [comment]
The Windows Subsystem for Linux allows native usage via Windows 11, Waydroid similarly for Linux.

The only way that this would be truly natively feasible would be with something akin to what padloc uses, but after using that software, you realize the limitations of it.

wxWidgets’ many projects that allow for degelation ultimately to native graphical toolkits remediate its problems somewhat, but it's only for desktop software, so it's not of much use for this project.

Additionally, all of that's only for the graphical interface.

This software is written in Java (for its underlying code) and Kotlin (for its interface, I expect) so it is very much native to Android, despite Java's support for many OSes, since those are Android's preferred development languages.

However, I must state that Bitwarden has managed to achieve almost code parity, it appears (to the extent possible), for its Android and iOS applications.

At the least, I consider an iOS application to be incredibly important because it shall also be installable on macOS and iPadOS, all of which are unable to easily virtualize Android how Waydroid and the ASL are.

**Comment by C10udburst** [comment]
> However, I must state that Bitwarden has managed to achieve almost code parity, it appears (to the extent possible), for its Android and iOS applications.

Bitwarden is writen in Xamarin, so it was designed as a cross platform app from the beginning.

As stated in #338 porting to native ios, windows, etc it would require for a complete rewrite of the app.

**Comment by LagradOst** [comment]
CS3 was never intended to be cross platform, cs2 was but xamarin sucks ass so cs2 it could not even be ported

**Comment by realgooseman** [comment]
If a desktop version is likely not planned, could there be some improvements in the app itself for desktop users ?

The app works great on Windows 11 with WSA, but a proper UI/UX for desktop usage with shortcuts (F=Full screen, Esc=Leave full screen, Volume control, ...) along with the other present layouts (Auto, Phone, TV, Emulator) would really make it all-in-one.

> The emulator layout is close to what could be a desktop version but it's not smooth enough and lacks shortcuts

**Comment by LagradOst** [comment]
> If a desktop version is likely not planned, could there be some improvements in the app itself for desktop users ?
> 
> The app works great on Windows 11 with WSA, but a proper UI/UX for desktop usage with shortcuts (F=Full screen, Esc=Leave full screen, Volume control, ...) along with the other present layouts (Auto, Phone, TV, Emulator) would really make it all-in-one.
> 
> > The emulator layout is close to what could be a desktop version but it's not smooth enough and lacks shortcuts

many keybindings already have actions https://github.com/recloudstream/cloudstream/blob/74060e7da32e0f8af23051149b383c92a6b1efb2/app/src/main/java/com/lagradost/cloudstream3/CommonActivity.kt#L479

**Comment by realgooseman** [comment]
Thanks for pointing those shortcuts out, I tried them and they work. However, the "F" key doesn't toggle full screen and "Esc" doesn't quit full-screen. F11 toggles full-screen for WSA apps in general, but "F" feels more natural as it's widely used for streaming services.

So maybe these would be nice to add : 

- F = full-screen toggle
- Esc = quit fullscreen or go back
- Page Up = go to the top of the page
- Page Down = go to the bottom of the page

Maybe a light UI refresh for desktop users, rework the pages to better suit usage on larger screens, Better scaling for movie/show covers as they're rather small*


> *I don't know if it's because I got a 4K monitor or if they need better scaling as they were not intended to be displayed on desktops screens.

**Comment by RokeJulianLockhart** [comment]
> F11 toggles full-screen for WSA apps in general, but "F" feels more natural as it's widely used for streaming services.

That seems silly to me. Perhaps if there's ever an option to manually set key bindings, but other than that, just use F11.
