### ISSUE TITLE
WTF!? Scumbag dev puts app on Playstore!

### ISSUE THREAD

**Issue by DarkCrypt** [recloudstream/cloudstream#267]
### Steps to reproduce

Sorry, this isn't an application issue but I wanted the devs to notice a different kind of issue. I apologize if I should of just messaged this to @LagradOst or posted this elsewhere but I wanted everyone to know.

I found a ripped version of CloudStream on the Playstore called cloudSteam! This is absolutely infuriating to me and I'm not even a participating dev! CloudStream is a bada** app built by some bada** devs and finding this ripped app on the Playstore is absolutely unacceptable. This scumbag changed the app slightly and put ads on it. I noticed the rip because of the screenshots.

I know CloudStream is open source and people can mostly do whatever they want as long as they don't infringe on the license but I don't like that this dev is getting credit and ad revenue from your hard work, especially from the Playstore. The real devs deserve all the credit and any funds that may go with it!

[https://play.google.com/store/apps/details?id=com.movie.cloudstream](url)

### Expected behavior

Help take down this app from the Playstore.

### Actual behavior

I've flagged, reported this app on the Playstore, and will continuously if needed.

### Cloudstream version and commit hash

n/a

### Android version

n/a

### Logcat

```java
n/a
```

### Other details

Maybe I'm going overboard about this issue, if I am let me know and I'll let it go.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by MustardChef** [comment]
This clone and many others are known by the devs.

**Comment by LagradOst** [comment]
Yep, not the first one. I think I have a list of at least 5 different apps on the playstore. It is against the licence, but nothing I can really do as trying to post any sort of dmca requires me to get actual lawyers involved and posting info about myself.

**Comment by midou221** [comment]
@LagradOst Why not publish cloudstream on the store...
does it violate store policy even though it does not provide any extensions when installing it?
Isn't it considered like IPTV applications?

**Comment by midou221** [comment]
> > Why not publish cloudstream on the store...
> 
> There's no good reason to and... FUCK Google.

But on play Store, he will be able to reach more users and achieve higher profits..
(also, I dont think the cloudstream in this form doesnt explicitly violate the store’s policy)

**Comment by Luna712** [comment]
I do not personally believe CloudStream should be published to Google Play. It's more work for devs to have to push updates. Additionally, I am more keen to just the source here that I can see rather than Google Play Store. Plus if someone really wants to find it, they will I don't believe to reach more users is necessarily a goal of this project but rather for personal use that someone can find if they really want to.

I do agree it may not violate policies — I have published apps on Play Store before — but I don't think the idea or rational behind it is actually something that is valid.

Just to note I am not officially attached to this project so it's not my choice. This is a purely personal opinion.

I can see it would be a very valid app on Play Store and can be beneficial I just don't believe it is worth it. Google also has to approve all updates before they are pushed live (IIRC anyway) which just makes this a whole mess and I don't really think working with Google on this is in anyone's best interests TBH…
