### ISSUE TITLE
subs sync

### ISSUE THREAD

**Issue by briantgosling** [recloudstream/cloudstream#406]
### Steps to reproduce

some sources doesn't sync subtitles
some sources doesn't have an audio
and some sources have different time of the movies(some have 1hour some have 55mins)

### Expected behavior

all should have synced subs and audios playing 

### Actual behavior

they dont

### Cloudstream version and commit hash

CloudStream 3.5.0

### Android version

android 12

### Logcat

```java
🐈
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
> some sources doesn't sync subtitles  and some sources have different time of the movies(some have 1hour some have 55mins)

We do not host any subtitles nor videos. This is uncontrollable and unfixable by us.

> some sources doesn't have an audio

Try opening in VLC, we need to add ffmpeg to support more codecs in the internal player, but the process is not trivial.

**Comment by asl97** [comment]
> > some sources doesn't sync subtitles  and some sources have different time of the movies(some have 1hour some have 55mins)
> 
> We do not host any subtitles nor videos. This is uncontrollable and unfixable by us.

The different timing issue isn't technically unfixable.

Sometimes rather than a standard offset (delay/early) in the subtitle, it's instead just the subtitle being created for a different length of video.

Wish there was an option to preprocess the subtitle to offset the timing by a percentage.

Basically there need to be two offset, one for when the subtitle starts, for when the video has fillers at the start and then a percentage offset.

```
movie:
_A-B--C
subtitle:
____A--B----C
2 offsets: 3 _ too late, and -50% timing shift.
result in remove []
offset start:
  _[___]
offset percentage -50%: 
  -[-]
  --[--]
result:
_A-B--C
```

The 1 video I seen of this issue needed around a 4% offset, ie: 1 second every 25 seconds
