### ISSUE TITLE
Downloaded video forcefully skips to random timestamps during playback.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [recloudstream/cloudstream#450]
### Steps to reproduce

1. Download https://solarmovie.pe/movie/watch-ghost-in-the-shell-free-19573

### Expected behavior

Playback should occur normally.

### Actual behavior

See the title. The user cannot prevent the skipping.

### Cloudstream version and commit hash

4.0.1 ded96dd9

### Android version

Android 12

### Other details

https://www.reddit.com/r/Piracy/comments/11kh6h0/cloudstream_beta_skipping_on_downloaded_movies/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by rokejulianlockhart** [comment]
I doubt that this is a provider issue.

**Comment by thushara5884** [comment]
Im getting the same issue. It is not a provider issue.  I tried multiple providers.

**Comment by Bishesh999** [comment]
Facing the same issue. Can't even download any movies

**Comment by asl97** [comment]
The simplest solution is to just add all the extension used, but if an provider wasn't faking it, it would result in corrupted files

Cloudstream would have to change the way they process m3u8 files, properly parsing it like how a player would, or maybe just throw it into third party app

Press and hold the episode/movie you want, click copy link, then use something like termux with youtube-dl/yt-dlp and paste the link into it

That works for me and it's multithreaded so it's also super fast

**Comment by asl97** [comment]
should be fixed by https://github.com/recloudstream/cloudstream/commit/590c74111cb945366ebd6a11278f2f9f827043c5#diff-63aeaa33233b064ed3811683a85a72a463d348ee312a1f8d6cea73a0c793353aR73

https://github.com/recloudstream/cloudstream/blob/6089cbc48493d746a110bba8d9997c3d2209b82e/app/src/main/java/com/lagradost/cloudstream3/utils/M3u8Helper.kt#L74

@rokejulianlockhart If this works for you, I guess you can just close this as fixed to keep the issue tracker neat.

@ScottWilliamAnderson care to explain the thumbdown?  is it a bad idea to add all or ignore the extension in the m3u8?

If you not happy with having to use the solution before the fix (above) was added, then that is just a bad reason to thumbdown, sometime we just need to make do with the situation and come up with the best solution available at the time and what I stated does work

**Comment by ScottWilliamAnderson** [comment]
Thanks for committing a change, that's always welcome.
I run cloudstream on a Chromecast, so copy pasting to an external downloader is not an option. 

![Screenshot_20230901-221102_GitHub~2.jpg](https://github.com/recloudstream/cloudstream/assets/47524721/12a17e5d-194a-4eed-8020-f98ad6553b52)

What's with the comment?

As long as there is already safeguards against streaming corrupted bytestrams, ignoring the extension type is hazardously tolerable.

**Comment by asl97** [comment]
> so copy pasting to an external downloader is not an option.

Just because it doesn't suit your ideal use case doesn't mean it's a bad idea that deserve a thumbdown, I am just another user who tries to give suggestion and from the thumbup from OP, this workaround worked for him and probably others use cases, before cloudstream maintainers 'fixed' it.

from the quick search I did, termux can be sideloaded onto a chromecast (probably one of the newer model), the fact that you have cloudstream probably mean you can sideload termux as well.

no where in my comment you thumbdown did I say cloudstream shouldn't fix this issue or bad suggestion that would warrent a thumbdown

the only thing I can think of is 'throwing it to a 3rd party app', which can be simply be implemented as a share link, which can be used with termux for downloading, and has the extra benefit of making it easier to use other players that handle links

**Comment by rokejulianlockhart** [comment]
https://github.com/recloudstream/cloudstream/issues/450#issuecomment-1703322436

> should be fixed by https://github.com/recloudstream/cloudstream/commit/590c74111cb945366ebd6a11278f2f9f827043c5#diff-63aeaa33233b064ed3811683a85a72a463d348ee312a1f8d6cea73a0c793353aR73

@asl97, if you are confident it's been fixed and are able to, you can close it. Otherwise, I'll close this when I next test it (if it works).
