### ISSUE TITLE
External Downloader

### ISSUE THREAD

**Issue by Livid96** [recloudstream/cloudstream#460]
### Describe your suggested feature

Please add external downloader option like 1DM for stable download.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by asl97** [comment]
Press and hold `play movie` or episode, and choose copy link

You can then paste that link into youtube-dl, yt-dlp, aria2 or any other apps

A option to replace the download button with a 'share' link feature would be nice since the built-in downloader is poor #450

The only issue with that and workarounds is you have to mark the episode as watched yourself afterwards

**Comment by salahxgamer** [comment]
Indeed the copy link works too, i also think if you set up your downloader app right you can make it open (as in share button @asl97 mentioned) by long clicking the play movie and choosing play in browser, either way is good enough

**Comment by rokejulianlockhart** [comment]
https://github.com/recloudstream/cloudstream/issues/460#issuecomment-1603977288

> Indeed the copy link works too, i also think if you set up your downloader app right you can make it open (as in share button @asl97 mentioned) by long clicking the play movie and choosing play in browser, either way is good enough

@salahxgamer, doesn't work for SuperStream though - https://codeberg.org/cloudstream/cloudstream-extensions/issues/18#issuecomment-849091
