### ISSUE TITLE
Mx player option 

### ISSUE THREAD

**Issue by Uvdon** [recloudstream/cloudstream#586]
### Describe your suggested feature

I have no problem with the in app player, however, I have noticed that it consumes a lot of battery unlike vlc or mxplayer. Vlc is great and all but it's very buggy. I would just like you to add mx player as an option to directly play videos from. Plz and thank you 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
mx is not open source

**Comment by asl97** [comment]
> mx is not open source

Nether is web video caster and both are bad in their own ways piracy wise and both are listed with ads

https://github.com/recloudstream/cloudstream/blob/6089cbc48493d746a110bba8d9997c3d2209b82e/app/src/main/java/com/lagradost/cloudstream3/MainActivity.kt#L173

They both have api via android intend

https://www.webvideocaster.app/integrations
https://mx.j2inter.com/api

then again, meh, I don't care about a random player with ads that collects so much data.

if implemented, the menu 'action' would need to try twice to open the app since there is two versions, not sure how complicated it would be, however I am strongly against adding two menu options for just this player even if it would avoid most of the complexity in the implementation. (even if I have no real say in how its implemented)

CC: @reduplicated because they added web video caster and they might be willing to add it
____

Address the battery usage issue, there is a big difference between [downloading and] playing a local file vs streaming battery usage.

you can actually try the copy link feature and get the stream link and try playing in mx player, assuming it actually support streaming and see if it's really VLC that's buggy or the provider you are using that is actually flaky, as well as compare battery usage.

**Comment by Uvdon** [comment]
Thanks for the reply. Yes, I have tested the same video link on both vlc and mx player. Both work fine actually, but the only main drop on vlc is that it does not properly work with forward and rewind buttons, unlike mx player. Also playing the same video on both the built in player and vlc or mx player (streaming) there is a huge difference in battery consumption; the built in player consumes -1% every 5 to 6 min, while vlc in my test consumes that in 8 to 9 min.

**Comment by asl97** [comment]
I hope you are aware that I am just another user and an unexplain thumbdown after who knows when, does not in fact incentives me to continue helping you, especially after the maintainer already said no and closes this issue.

I am also kind of already regretting bothering to even ping the person who added support for another close source app due to said thumbdown, for the unlikely chances they might actually be interested due to the fact, it is actual possible to add support unlike most close source app because there is an api which I mentioned in the comment you thumbdown.

cloudstream is targeting a lot of device with the primary support seemingly low end always plug in devices so it's default isn't tuned to make use of larger buffer which can reduce overall power usage.

beside, there is already support for mpv, which is the only other player that successfully seek while disconnected from the internet, not vlc, no internal, not even mx player successfully seek more than a few times back and forward before it stop with a reload/buffering icon.

people like you with their random thumbdown and down votes are the reason helpful people loses interest in giving their time to attempt to help.

**Comment by LagradOst** [comment]
@asl97 webvideo was added because only because the internal chromecast does not work for some ppl due to us not having paid $5 registration fee and was denied when first requested due to same issue. I am 100% on board to remove it due to the ads/tracking reason, but due to the unstable chomecast api it simply can not be removed. We already have 3 open source app players (inapp, vlc and mpv) so I dont see a reason to add a closed source ad/paid app

**Comment by asl97** [comment]
@LagradOst thanks for taking the time to claify the exception given to web video cast.

There wasn't any specific issue or pull request that stood out to me nor comments by the author, reduplicated, as far as I can tell, that contain said reason.

I can see the few very limited use cases for web video cast
  1. I am assuming it has a remote/different network casting feature due to the youtube-tv/zoom like feature of code entering, for security purpose or whatever where you don't wish to give guest access to your network for casting.
  2. tv/device isn't actually an 'android tv' and thus lack the 'receiver', and require using a third party app/web browser.

<details>
<summary>Slightly off topic about casting and further ranting</summary>

I don't think paying the $5 would do anything to improve the casting situation, it doesn't really unlock any specific playback feature when used with the builtin chromecast on device like tv.

To have some effect would require a custom receiver (basically a web app) or separate receiver app, in which case, it basically do whatever it needs without needing to depend on chromecast api.

Which I am aware you already said you probably wouldn't do it in https://github.com/recloudstream/cloudstream/issues/32#issuecomment-1399345312.

Beside that doesn't actually solve case (1), which needs so much work and infrastructure for such rare use case.

for local network streaming casting with supported devices, the other two options are fine
1. inapp, (exoplayer, now called media3)
2. web browser, which sees two end point, one is probably the default and other the 'chrome' receiver

While vlc really suck at casting for streaming, it seem to do the local restreaming (it might even be doing transcoding, which would be really bad for battery life), it's the only option for casting local file that I know without needing another app on the receiving side like kodi+air play client (droidplay) (local network only) or in this case, web video cast and it's receiver app.

I guess one can run a http server or something and uses vlc/web browser on the receiving side but that's probably expecting too much from the end user.

At that point, might as well just send the file over with nearby share/wifi direct and play it locally, much simpler.
</details>

**Comment by LagradOst** [comment]
> @LagradOst thanks for taking the time to claify the exception given to web video cast.
> 
> There wasn't any specific issue or pull request that stood out to me nor comments by the author, reduplicated, as far as I can tell, that contain said reason.
> 
> I can see the few very limited use cases for web video cast
>   1. I am assuming it has a remote/different network casting feature due to the youtube-tv/zoom like feature of code entering, for security purpose or whatever where you don't wish to give guest access to your network for casting.
>   2. tv/device isn't actually an 'android tv' and thus lack the 'receiver', and require using a third party app/web browser.
> 
> <details>
> <summary>Slightly off topic about casting and further ranting</summary>
> 
> I don't think paying the $5 would do anything to improve the casting situation, it doesn't really unlock any specific playback feature when used with the builtin chromecast on device like tv.
> 
> To have some effect would require a custom receiver (basically a web app) or separate receiver app, in which case, it basically do whatever it needs without needing to depend on chromecast api.
> 
> Which I am aware you already said you probably wouldn't do it in https://github.com/recloudstream/cloudstream/issues/32#issuecomment-1399345312.
> 
> Beside that doesn't actually solve case (1), which needs so much work and infrastructure for such rare use case.
> 
> for local network streaming casting with supported devices, the other two options are fine
> 1. inapp, (exoplayer, now called media3)
> 2. web browser, which sees two end point, one is probably the default and other the 'chrome' receiver
> 
> While vlc really suck at casting for streaming, it seem to do the local restreaming (it might even be doing transcoding, which would be really bad for battery life), it's the only option for casting local file that I know without needing another app on the receiving side like kodi+air play client (droidplay) (local network only) or in this case, web video cast and it's receiver app.
> 
> I guess one can run a http server or something and uses vlc/web browser on the receiving side but that's probably expecting too much from the end user.
> 
> At that point, might as well just send the file over with nearby share/wifi direct and play it locally, much simpler.
> </details>

2 dmcas removed 1k+ issues. web video is to chromecast from a mobile phone to a reciver tv (not android tv) and when cs3 can do that flawless it will be removed

**Comment by LagradOst** [comment]
mx player is never going to be added, and if you feel like that is a dealbreaker then you can fork the app and add it yourself

**Comment by Uvdon** [comment]
Mpv don't have seek buttons

**Comment by asl97** [comment]
> Mpv don't have seek buttons

you just make yourself look like a idiot, maybe try googling.

mpv support seeking with a remote control arrow key and keyboard, so that cover most of android box and android tv.

If you are asking for a button, I would assume you have touch, in which case you have both double tap and drag seeking, both are ways of seeking in vlc too, with youtube using double tapping only.

![Screenshot_2023-09-02-14-19-10-795_is xyz mpv](https://github.com/recloudstream/cloudstream/assets/4752645/06dec885-4d10-467d-9a6a-8c2a22726b11)

Now, if you only have mouse control, guess what? It works too with the above.

So what legitimate reason do you need actual seek buttons?

Do you have OCD and need to have buttons which youtube don't even have?

Or are you just trying to make a fuss just because we don't want mx player intergrated with cloudstream.
