### ISSUE TITLE
High resolution videos lag (but I know the fix!)

### ISSUE THREAD

**Issue by StupidRepo** [recloudstream/cloudstream#588]
So basically I've seen this issue before in video players. In VLC you can fix this lag by enabling hardware acceleration but only for decoding.

If you guys can figure out how to add an option that allows for hardware acceleration on the decoding/displaying video, then please add it so you can fix this lag.

If anyone knows a universal fix for this (a magisk module, etc.), then please tell me because I would love to fix this in every video player.

**Comment by LagradOst** [comment]
cs3 uses exoplayer and exo should use hw decoding

**Comment by asl97** [comment]
There is no such universe fix via a system patch (magisk module) , we are talking about very specific buffering and processing of video data that is very dependent on each player implementation.

One of the ways you can try to reduce lag spike is by increasing buffer size if your device has the ram for it, larger buffer means it has more time to process the data heavy parts of the video before it need to show on screen.

Another hack is to reduce playback speed, while not a great solution, it does allow stupidly large video to playback on less powerful devices, it works the same way, allowing the device more time to process.

**Comment by LagradOst** [comment]
@StupidRepo 💀 💀 💀 💀 bro that is not how it works. the big 3 exo, vlc and mpv use completely different decoding frameworks, you wont be able to simply pull code from one and put it in another

**Comment by LagradOst** [comment]
your "suggestions" are like chatgpt advice

**Comment by Blatzar** [comment]
> Hm, strange. The only thing I can suggest is looking at VLC source code (if it's public) and seeing how they handle the decoding process, and then trying to adapt it (or PR it into exoplayer)

Decoding in general is a very elaborate process done at a very low level for the greatest speed. Simply understanding everything to adapt would be a big project, not to mention doing any sort of porting. It is like asking your local family owned grocery store to research CRISPR gene editing to make their apples taste better, perhaps possible with much dedication, but out of scope and better left to the real researchers. The idea is certainly valid and could improve stuff, but it is not worth it by a long stretch.

The wording does not matter given the fundamental infeasibility, and I am pretty sure LagradOst knows of editing. Extremely hash comment from him, but responding like that yourself is not much better, and I am sure you do not think of yourself as a horrible person. I am also sure you do not enjoy insulting people. 

I suggest making an issue in their repository with any ideas you might have regarding improving exoplayer itself :+1: 
I would love if you made it better :pray:

**Comment by asl97** [comment]
> It is like asking your local family owned grocery store to research CRISPR gene editing to make their apples taste better, 

@Blatzar technically, even if the store learns how, it wouldn't help much as they don't actually grows their apple.

They could make it better by processing the apple into other products like apple pie and apple chips (ie, better defaults and wider niche format support).

> Also, your dumb ass doesn't even know how to use the GitHub edit feature, seeing that you made 2 different comments instead of editing the one. Here, let me help you with that too.

@StupidRepo YOUR dumb ass failed to understand the reason for the second comment, the fact your 'suggestion' was so bad, it was 'important' enough to have it notify everyone who watches this repo instead of just for those who check if the comment been edited afterwards.

In case you didn't know, Youtube app on android uses exo player internally, it's like saying google and everyone else using it is stupid enough not to have hardware decoding already enable when possible.
____

Increase the buffer, pause the playback for sometime so it had a chance to built up the buffer then you can resume the playback.

The default prebuffer before playing is fairly small, but I don't think everyone deserve having to wait longer by using a larger default because your device sucks

https://github.com/recloudstream/cloudstream/blob/6211b02e85b0dcd4ab5a2954623917e8c27ba552/app/src/main/java/com/lagradost/cloudstream3/ui/player/CS3IPlayer.kt#L751

https://developer.android.com/reference/androidx/media3/exoplayer/DefaultLoadControl#DEFAULT_BUFFER_FOR_PLAYBACK_MS()

**Comment by b1bradders** [comment]
Was having issues with a stream today, and found this issue. I do not remember commenting on this issue and also being quite rude about it lol.

Whilst I'm here, sorry for being crazily rude 😭 I think I was a little annoyed by something else that day and so I just dumped the anger into that comment (although LagradOst did provoke me, but it was mainly me being annoyed that prompted me to make the follow-up comment).

Anyway, yeah, sorry for that 😅
