### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by EHMilon** [recloudstream/cloudstream#589]
### Need some UI improvement in this app:
1. **Header image slight automatically switch**
![Screenshot_20230902-133900~2](https://github.com/recloudstream/cloudstream/assets/107425940/047ac812-2184-43db-b52b-a0ee8e7d5ecd)
2. **Search suggestion**
![Screenshot_20230902-140438~2](https://github.com/recloudstream/cloudstream/assets/107425940/0f4ea771-7dda-4914-b7cd-8195f3c7464f)
![Screenshot_20230902-140802~2](https://github.com/recloudstream/cloudstream/assets/107425940/2ae14183-d3d2-4092-82c2-27e14025d08f) 
**Provider search suggestion:**
![Screenshot_20230902-142129~2](https://github.com/recloudstream/cloudstream/assets/107425940/814e2a6b-34d7-480d-b4bd-bce08fb122ee)
3. **Provider filter search.**
![Screenshot_20230902-135914~2](https://github.com/recloudstream/cloudstream/assets/107425940/26275bc5-396c-445d-913c-3befed3dcb33)
![Screenshot_20230902-140116~3](https://github.com/recloudstream/cloudstream/assets/107425940/272dbf66-df9e-4f1c-9daa-773fab8c63fa)
4. **Movie, TV series icon and font size make small.
Movie's name front color should be different**.
![Screenshot_20230902-134759~2](https://github.com/recloudstream/cloudstream/assets/107425940/bce9a795-51d3-460e-95cb-ef918835a93d)
5. **Footer icons:**
![Screenshot_20230902-142839~2](https://github.com/recloudstream/cloudstream/assets/107425940/47d3a59e-a04b-4d56-b21b-883f1479c00f)
![Screenshot_20230902-143052~2](https://github.com/recloudstream/cloudstream/assets/107425940/7d066b8c-bc17-479f-8f63-77e78ea8b57f)

_Reference: onStream and HDO Box app_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
na fam, that shit is ulgy af

**Comment by asl97** [comment]
> na fam, that shit is ulgy af
As funny as your reply is, (insert let me do it for you meme).

Here a more proper closing reasons
____

You are aware that cloudstream don't contain the videos or providers and most of those features would depend on them third party providers implementing it, assuming upstream sources even support those features.

You can compare it with search feature of tachiyomi, global search, no provider specific search filter, while for individual search, only very few extensions actually implement their specific filter, you end up needing to use web view for those that don't to be able to use filters offered by the sources website

Not to mention, as far as I know, providers are still kind of in limbo, and some provider technically don't source from an actual website.

Some of those feature you listed already exists, either currently or in the past

1. the loading back drop suggest it used to look like this, if you are asking for it to automatically swtich/slide to the next poster,  no comment

2. it exists in form of 'popular movie/series' for some providers

3. there is a 'hide selected video quality in search result' in the settings, other than that, it is highly dependent on the provider. It's a lot of work to add such an api and providers might just not implement them,  just open the provider source website of your choice and use their search and once you have a title, you can search for it in cloudstream. if the source website doesn't have said search feature or even a website, neither cloudstream nor the provider can magically add it either

4. set your device text smaller, or you can make use of the 'postal title location' in the settings to make it more compact

5. you can press and hold those button to get their name, not sure why you would want the actual word on screen since you asked for a more dense screen (4)
