### ISSUE TITLE
Random button functionality broken.

### ISSUE THREAD

**Issue by Akv2021** [recloudstream/cloudstream#78]
### Steps to reproduce

1. Launch cloudstream beta and Random button disappears after homepage is loaded.
2. Toggling "Show Random button on homepage" does not make any difference.
3. On filter provider on homepage, select "random" option. It resets provider to "none".

### Expected behavior

There is an issue with both the "Show random button on homepage" option (Floating action button on left on homepage) and "Random" option in Provider chooser (Floating action button on right on homescreen which is used to choose provider to show contents from on homepage).
Expected - 
1. Show random button(LHS FAB) - should randomly open view page of a movie/series 
2. Random option (In RHS FAB) - should randomly choose a provider based in category chosen (i.e. movie/series etc)

Both behaviours are working as expected in the last stable release of cloudstream (v 3.0.0)

### Actual behavior

1. Show random button(LHS FAB) - sometimes briefly shows up when app is launched but always disappears after homepage is loaded.
2. Random option (In RHS FAB) - selects "none" as provider.

### Cloudstream version and commit hash

3.1.4 cdf0047

### Android version

Android 9

### Logcat

```java
NA
```

### Other details

NA

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Jacekun** [comment]
It becomes invisible cause of this line:
https://github.com/recloudstream/cloudstream/blob/cdf0047bfdc899545b2330339fd0d2cc9ab05c79/app/src/main/java/com/lagradost/cloudstream3/ui/home/HomeFragment.kt#L626

and since when a new homepage is loaded, it refreshes the list:
https://github.com/recloudstream/cloudstream/blob/cdf0047bfdc899545b2330339fd0d2cc9ab05c79/app/src/main/java/com/lagradost/cloudstream3/ui/home/HomeFragment.kt#L614

it will always be toggled off.

It'll need to adjust the code hierarchy so that the toggle will only execute after the homepage is loaded from currently loaded plugin provider.

**Comment by Jacekun** [comment]
Upon further inspection, I'm kinda talking my ass off here. Will PR a fix for this.
