### ISSUE TITLE
SIMKL syncing error with Cloudstream 

### ISSUE THREAD

**Issue by aghostbehindyou** [recloudstream/cloudstream#784]
### Steps to reproduce

1. Link Cloudstream account with SIMKL account.
2. Add a TV show to SIMKL.
3. Using Cloudstream, stream an episode of a TV show in a series and watch or scrub to the end e.g. Season 25 Episode 5 of the Simpsons.
4. Let SIMKL automatically detect the episode has been fully watched.

### Expected behavior

SIMKL is supposed to mark ONLY Season 25 Episode 5 as watched.

### Actual behavior

SIMKL marks ALL previous episodes as watched. That is, it marks Seasons 25 episode 5 downwards as watched. Basically, the issue occurs when you watch series in a descending order.

### Cloudstream version and commit hash

4.2.1 fa7ebc0

### Android version

Android 13

### Logcat

```java
https://pastebin.com/C54hR2XH
```

### Other details

I raised this issue on the SIMKL subreddit, this was the response i got "You should contact the Cloudstream3 app developer as that app is sending what you watched, nothing Simkl can do"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Yes, this is the correct place to report this, simkl cannot control this.

No, this is actually expected behavior.

Cloudstream has a simpler episode system where you only set number of episodes seen, as a consequence of this the fine grained approach simkl offers gets lost. 

Our system is partly because of ease of use, legacy design from when there was only MAL and Anilist, and the fact that supporting such a system UI wise is a lot of effort.

**Comment by aghostbehindyou** [comment]
Understood. I hope one day I could be streamlined. Kudos to the Cloudstream3 developers.
