### ISSUE TITLE
Add an option to select external video player

### ISSUE THREAD

**Issue by asurpbs** [recloudstream/cloudstream#899]
### Describe your suggested feature

I suggest adding an option to select an external video player instead of VLC and MPV individual options the Cloudstream app. When the user clicks on this option, a dialog box should appear that recommends MPV and VLC players as they are more compatible with these stream links. The dialog box should have an “OK” button to continue. After clicking “OK”, the user can select their preferred video player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
bro, just longclick the episode and you will get a menu to select exactly how you want to play the content, open in browser even shows all the videoplayers on the phone

**Comment by asl97** [comment]
Open in browser doesn't show that on all devices, at least not mine, it just open in the default browser

Unless the video is in a format not supported by the browser, only then it will either download the file or ask which app it should open in the link with.

I am still advocating for what I said in another issue, there is clearly a demand for a quick way to open in any properly implemented app, instead of `copy link, open app, paste link` or `open in browser, share url` workarounds.

https://github.com/recloudstream/cloudstream/issues/747#issuecomment-1791719328
> Honestly, I rather advocate for changing 'copy link' to 'share link' as the share menu include but not limited to 'copy to clipboard', vlc and other media players.
> 
> It would be a suitable substitute to this and other issues.

PS TLDL: This is related to #747 and #460
